name: Athena
description: Aegis' custom Java plugin
main: net.aegis.athena.Athena
version: '1.1'
authors:
  - Cynshiii
  - WakkaFlocka
  - GriffinCodes
api-version: 1.19
load: POSTWORLD
depend:
  - helper
  - mcMMO
  - Multiverse-Core
  - ProtocolLib
  - WorldGuard
softdepend:
  - BuycraftX
  - Citizens
  - HeadDatabase
  - HolographicDisplays
  - LibsDisguises
  - Multiverse-Inventories
  - NBTAPI
  - PlaceholderAPI
  - spark
  - Vault
  - Votifier